version: '3.8'
services:
  mysql-service:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=capstonedb
    ports:
      - 3307:3306
    restart: always
  java-service:
    build: ./backend/mvb-app
    container_name: mvb-app
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    ports:
      - 9090:9090
    depends_on:
      - mysql-service
    restart: always
  angular-service:
    build: ./frontend
    container_name: angular_container
    ports:
      - 81:80
   
  